// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: course/v1/course.proto

package coursev1

import (
	v1 "github.com/Newterios/lms-system-prob/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TeacherId     string                 `protobuf:"bytes,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_course_v1_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *Course) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Course) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Course) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_course_v1_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{1}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type Material struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     string                 `protobuf:"bytes,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "pdf" | "video" | "link"
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_course_v1_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{2}
}

func (x *Material) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Material) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *Material) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Material) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Material) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Enrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	EnrolledAt    string                 `protobuf:"bytes,4,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enrollment) Reset() {
	*x = Enrollment{}
	mi := &file_course_v1_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enrollment) ProtoMessage() {}

func (x *Enrollment) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enrollment.ProtoReflect.Descriptor instead.
func (*Enrollment) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{3}
}

func (x *Enrollment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enrollment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Enrollment) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Enrollment) GetEnrolledAt() string {
	if x != nil {
		return x.EnrolledAt
	}
	return ""
}

// 1. CreateCourse — teacher_id comes from JWT.
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_v1_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_v1_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// 2. GetCourse
type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_course_v1_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{6}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_course_v1_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{7}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// 3. UpdateCourse — only the editable metadata fields.
type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_course_v1_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_course_v1_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// 4. DeleteCourse — soft-delete (sets deleted_at).
type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_course_v1_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_course_v1_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{11}
}

// 5. ListCourses — optional teacher_id filter for "my courses" views.
type ListCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.Pagination         `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	TeacherId     *string                `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3,oneof" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesRequest) Reset() {
	*x = ListCoursesRequest{}
	mi := &file_course_v1_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesRequest) ProtoMessage() {}

func (x *ListCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesRequest.ProtoReflect.Descriptor instead.
func (*ListCoursesRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{12}
}

func (x *ListCoursesRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCoursesRequest) GetTeacherId() string {
	if x != nil && x.TeacherId != nil {
		return *x.TeacherId
	}
	return ""
}

type ListCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesResponse) Reset() {
	*x = ListCoursesResponse{}
	mi := &file_course_v1_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesResponse) ProtoMessage() {}

func (x *ListCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesResponse.ProtoReflect.Descriptor instead.
func (*ListCoursesResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{13}
}

func (x *ListCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *ListCoursesResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// 6. CreateSection
type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_course_v1_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSectionRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSectionRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionResponse) Reset() {
	*x = CreateSectionResponse{}
	mi := &file_course_v1_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionResponse) ProtoMessage() {}

func (x *CreateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSectionResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSectionResponse) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

// 7. ListSections — small bounded list per course, no pagination.
type ListSectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSectionsRequest) Reset() {
	*x = ListSectionsRequest{}
	mi := &file_course_v1_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSectionsRequest) ProtoMessage() {}

func (x *ListSectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSectionsRequest.ProtoReflect.Descriptor instead.
func (*ListSectionsRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{16}
}

func (x *ListSectionsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ListSectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSectionsResponse) Reset() {
	*x = ListSectionsResponse{}
	mi := &file_course_v1_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSectionsResponse) ProtoMessage() {}

func (x *ListSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSectionsResponse.ProtoReflect.Descriptor instead.
func (*ListSectionsResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{17}
}

func (x *ListSectionsResponse) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

// 8. AddMaterial
type AddMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialRequest) Reset() {
	*x = AddMaterialRequest{}
	mi := &file_course_v1_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialRequest) ProtoMessage() {}

func (x *AddMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialRequest.ProtoReflect.Descriptor instead.
func (*AddMaterialRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{18}
}

func (x *AddMaterialRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *AddMaterialRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddMaterialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddMaterialRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AddMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialResponse) Reset() {
	*x = AddMaterialResponse{}
	mi := &file_course_v1_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialResponse) ProtoMessage() {}

func (x *AddMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialResponse.ProtoReflect.Descriptor instead.
func (*AddMaterialResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{19}
}

func (x *AddMaterialResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

// 9. ListMaterials
type ListMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsRequest) Reset() {
	*x = ListMaterialsRequest{}
	mi := &file_course_v1_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsRequest) ProtoMessage() {}

func (x *ListMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsRequest.ProtoReflect.Descriptor instead.
func (*ListMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{20}
}

func (x *ListMaterialsRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

type ListMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*Material            `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsResponse) Reset() {
	*x = ListMaterialsResponse{}
	mi := &file_course_v1_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsResponse) ProtoMessage() {}

func (x *ListMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsResponse.ProtoReflect.Descriptor instead.
func (*ListMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{21}
}

func (x *ListMaterialsResponse) GetMaterials() []*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

//  10. EnrollStudent — student_id stays explicit to support both self-enroll
//     and teacher-driven enroll (the usecase enforces the role check).
type EnrollStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollStudentRequest) Reset() {
	*x = EnrollStudentRequest{}
	mi := &file_course_v1_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollStudentRequest) ProtoMessage() {}

func (x *EnrollStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollStudentRequest.ProtoReflect.Descriptor instead.
func (*EnrollStudentRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{22}
}

func (x *EnrollStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *EnrollStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type EnrollStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *Enrollment            `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollStudentResponse) Reset() {
	*x = EnrollStudentResponse{}
	mi := &file_course_v1_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollStudentResponse) ProtoMessage() {}

func (x *EnrollStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollStudentResponse.ProtoReflect.Descriptor instead.
func (*EnrollStudentResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{23}
}

func (x *EnrollStudentResponse) GetEnrollment() *Enrollment {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

// 11. UnenrollStudent
type UnenrollStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnenrollStudentRequest) Reset() {
	*x = UnenrollStudentRequest{}
	mi := &file_course_v1_course_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnenrollStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnenrollStudentRequest) ProtoMessage() {}

func (x *UnenrollStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnenrollStudentRequest.ProtoReflect.Descriptor instead.
func (*UnenrollStudentRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{24}
}

func (x *UnenrollStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UnenrollStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type UnenrollStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnenrollStudentResponse) Reset() {
	*x = UnenrollStudentResponse{}
	mi := &file_course_v1_course_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnenrollStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnenrollStudentResponse) ProtoMessage() {}

func (x *UnenrollStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnenrollStudentResponse.ProtoReflect.Descriptor instead.
func (*UnenrollStudentResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{25}
}

//  12. ListEnrollments — optional filters by course_id and/or student_id.
//     Used both by the gradebook UI and as a "check enrollment" by
//     assessment-svc-v2 (empty enrollments slice ⇒ not enrolled).
type ListEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      *string                `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	StudentId     *string                `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3,oneof" json:"student_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsRequest) Reset() {
	*x = ListEnrollmentsRequest{}
	mi := &file_course_v1_course_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsRequest) ProtoMessage() {}

func (x *ListEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{26}
}

func (x *ListEnrollmentsRequest) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetStudentId() string {
	if x != nil && x.StudentId != nil {
		return *x.StudentId
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*Enrollment          `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsResponse) Reset() {
	*x = ListEnrollmentsResponse{}
	mi := &file_course_v1_course_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsResponse) ProtoMessage() {}

func (x *ListEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_v1_course_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_course_v1_course_proto_rawDescGZIP(), []int{27}
}

func (x *ListEnrollmentsResponse) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *ListEnrollmentsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_course_v1_course_proto protoreflect.FileDescriptor

const file_course_v1_course_proto_rawDesc = "" +
	"\n" +
	"\x16course/v1/course.proto\x12\tcourse.v1\x1a\x16common/v1/common.proto\"\xc9\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x04 \x01(\tR\tteacherId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"h\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"u\n" +
	"\bMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\tR\tsectionId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"y\n" +
	"\n" +
	"Enrollment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x1f\n" +
	"\venrolled_at\x18\x04 \x01(\tR\n" +
	"enrolledAt\"i\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"A\n" +
	"\x14CreateCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course\"y\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"A\n" +
	"\x14UpdateCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteCourseResponse\"~\n" +
	"\x12ListCoursesRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.common.v1.PaginationR\n" +
	"pagination\x12\"\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tH\x00R\tteacherId\x88\x01\x01B\r\n" +
	"\v_teacher_id\"t\n" +
	"\x13ListCoursesResponse\x12+\n" +
	"\acourses\x18\x01 \x03(\v2\x11.course.v1.CourseR\acourses\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo\"e\n" +
	"\x14CreateSectionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"E\n" +
	"\x15CreateSectionResponse\x12,\n" +
	"\asection\x18\x01 \x01(\v2\x12.course.v1.SectionR\asection\"2\n" +
	"\x13ListSectionsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"F\n" +
	"\x14ListSectionsResponse\x12.\n" +
	"\bsections\x18\x01 \x03(\v2\x12.course.v1.SectionR\bsections\"o\n" +
	"\x12AddMaterialRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"F\n" +
	"\x13AddMaterialResponse\x12/\n" +
	"\bmaterial\x18\x01 \x01(\v2\x13.course.v1.MaterialR\bmaterial\"5\n" +
	"\x14ListMaterialsRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\"J\n" +
	"\x15ListMaterialsResponse\x121\n" +
	"\tmaterials\x18\x01 \x03(\v2\x13.course.v1.MaterialR\tmaterials\"R\n" +
	"\x14EnrollStudentRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"N\n" +
	"\x15EnrollStudentResponse\x125\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2\x15.course.v1.EnrollmentR\n" +
	"enrollment\"T\n" +
	"\x16UnenrollStudentRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"\x19\n" +
	"\x17UnenrollStudentResponse\"\xb2\x01\n" +
	"\x16ListEnrollmentsRequest\x12 \n" +
	"\tcourse_id\x18\x01 \x01(\tH\x00R\bcourseId\x88\x01\x01\x12\"\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tH\x01R\tstudentId\x88\x01\x01\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.common.v1.PaginationR\n" +
	"paginationB\f\n" +
	"\n" +
	"_course_idB\r\n" +
	"\v_student_id\"\x84\x01\n" +
	"\x17ListEnrollmentsResponse\x127\n" +
	"\venrollments\x18\x01 \x03(\v2\x15.course.v1.EnrollmentR\venrollments\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo2\xe7\a\n" +
	"\rCourseService\x12O\n" +
	"\fCreateCourse\x12\x1e.course.v1.CreateCourseRequest\x1a\x1f.course.v1.CreateCourseResponse\x12F\n" +
	"\tGetCourse\x12\x1b.course.v1.GetCourseRequest\x1a\x1c.course.v1.GetCourseResponse\x12O\n" +
	"\fUpdateCourse\x12\x1e.course.v1.UpdateCourseRequest\x1a\x1f.course.v1.UpdateCourseResponse\x12O\n" +
	"\fDeleteCourse\x12\x1e.course.v1.DeleteCourseRequest\x1a\x1f.course.v1.DeleteCourseResponse\x12L\n" +
	"\vListCourses\x12\x1d.course.v1.ListCoursesRequest\x1a\x1e.course.v1.ListCoursesResponse\x12R\n" +
	"\rCreateSection\x12\x1f.course.v1.CreateSectionRequest\x1a .course.v1.CreateSectionResponse\x12O\n" +
	"\fListSections\x12\x1e.course.v1.ListSectionsRequest\x1a\x1f.course.v1.ListSectionsResponse\x12L\n" +
	"\vAddMaterial\x12\x1d.course.v1.AddMaterialRequest\x1a\x1e.course.v1.AddMaterialResponse\x12R\n" +
	"\rListMaterials\x12\x1f.course.v1.ListMaterialsRequest\x1a .course.v1.ListMaterialsResponse\x12R\n" +
	"\rEnrollStudent\x12\x1f.course.v1.EnrollStudentRequest\x1a .course.v1.EnrollStudentResponse\x12X\n" +
	"\x0fUnenrollStudent\x12!.course.v1.UnenrollStudentRequest\x1a\".course.v1.UnenrollStudentResponse\x12X\n" +
	"\x0fListEnrollments\x12!.course.v1.ListEnrollmentsRequest\x1a\".course.v1.ListEnrollmentsResponseB?Z=github.com/Newterios/lms-system-prob/proto/course/v1;coursev1b\x06proto3"

var (
	file_course_v1_course_proto_rawDescOnce sync.Once
	file_course_v1_course_proto_rawDescData []byte
)

func file_course_v1_course_proto_rawDescGZIP() []byte {
	file_course_v1_course_proto_rawDescOnce.Do(func() {
		file_course_v1_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_v1_course_proto_rawDesc), len(file_course_v1_course_proto_rawDesc)))
	})
	return file_course_v1_course_proto_rawDescData
}

var file_course_v1_course_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_course_v1_course_proto_goTypes = []any{
	(*Course)(nil),                  // 0: course.v1.Course
	(*Section)(nil),                 // 1: course.v1.Section
	(*Material)(nil),                // 2: course.v1.Material
	(*Enrollment)(nil),              // 3: course.v1.Enrollment
	(*CreateCourseRequest)(nil),     // 4: course.v1.CreateCourseRequest
	(*CreateCourseResponse)(nil),    // 5: course.v1.CreateCourseResponse
	(*GetCourseRequest)(nil),        // 6: course.v1.GetCourseRequest
	(*GetCourseResponse)(nil),       // 7: course.v1.GetCourseResponse
	(*UpdateCourseRequest)(nil),     // 8: course.v1.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),    // 9: course.v1.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),     // 10: course.v1.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),    // 11: course.v1.DeleteCourseResponse
	(*ListCoursesRequest)(nil),      // 12: course.v1.ListCoursesRequest
	(*ListCoursesResponse)(nil),     // 13: course.v1.ListCoursesResponse
	(*CreateSectionRequest)(nil),    // 14: course.v1.CreateSectionRequest
	(*CreateSectionResponse)(nil),   // 15: course.v1.CreateSectionResponse
	(*ListSectionsRequest)(nil),     // 16: course.v1.ListSectionsRequest
	(*ListSectionsResponse)(nil),    // 17: course.v1.ListSectionsResponse
	(*AddMaterialRequest)(nil),      // 18: course.v1.AddMaterialRequest
	(*AddMaterialResponse)(nil),     // 19: course.v1.AddMaterialResponse
	(*ListMaterialsRequest)(nil),    // 20: course.v1.ListMaterialsRequest
	(*ListMaterialsResponse)(nil),   // 21: course.v1.ListMaterialsResponse
	(*EnrollStudentRequest)(nil),    // 22: course.v1.EnrollStudentRequest
	(*EnrollStudentResponse)(nil),   // 23: course.v1.EnrollStudentResponse
	(*UnenrollStudentRequest)(nil),  // 24: course.v1.UnenrollStudentRequest
	(*UnenrollStudentResponse)(nil), // 25: course.v1.UnenrollStudentResponse
	(*ListEnrollmentsRequest)(nil),  // 26: course.v1.ListEnrollmentsRequest
	(*ListEnrollmentsResponse)(nil), // 27: course.v1.ListEnrollmentsResponse
	(*v1.Pagination)(nil),           // 28: common.v1.Pagination
	(*v1.PageInfo)(nil),             // 29: common.v1.PageInfo
}
var file_course_v1_course_proto_depIdxs = []int32{
	0,  // 0: course.v1.CreateCourseResponse.course:type_name -> course.v1.Course
	0,  // 1: course.v1.GetCourseResponse.course:type_name -> course.v1.Course
	0,  // 2: course.v1.UpdateCourseResponse.course:type_name -> course.v1.Course
	28, // 3: course.v1.ListCoursesRequest.pagination:type_name -> common.v1.Pagination
	0,  // 4: course.v1.ListCoursesResponse.courses:type_name -> course.v1.Course
	29, // 5: course.v1.ListCoursesResponse.page_info:type_name -> common.v1.PageInfo
	1,  // 6: course.v1.CreateSectionResponse.section:type_name -> course.v1.Section
	1,  // 7: course.v1.ListSectionsResponse.sections:type_name -> course.v1.Section
	2,  // 8: course.v1.AddMaterialResponse.material:type_name -> course.v1.Material
	2,  // 9: course.v1.ListMaterialsResponse.materials:type_name -> course.v1.Material
	3,  // 10: course.v1.EnrollStudentResponse.enrollment:type_name -> course.v1.Enrollment
	28, // 11: course.v1.ListEnrollmentsRequest.pagination:type_name -> common.v1.Pagination
	3,  // 12: course.v1.ListEnrollmentsResponse.enrollments:type_name -> course.v1.Enrollment
	29, // 13: course.v1.ListEnrollmentsResponse.page_info:type_name -> common.v1.PageInfo
	4,  // 14: course.v1.CourseService.CreateCourse:input_type -> course.v1.CreateCourseRequest
	6,  // 15: course.v1.CourseService.GetCourse:input_type -> course.v1.GetCourseRequest
	8,  // 16: course.v1.CourseService.UpdateCourse:input_type -> course.v1.UpdateCourseRequest
	10, // 17: course.v1.CourseService.DeleteCourse:input_type -> course.v1.DeleteCourseRequest
	12, // 18: course.v1.CourseService.ListCourses:input_type -> course.v1.ListCoursesRequest
	14, // 19: course.v1.CourseService.CreateSection:input_type -> course.v1.CreateSectionRequest
	16, // 20: course.v1.CourseService.ListSections:input_type -> course.v1.ListSectionsRequest
	18, // 21: course.v1.CourseService.AddMaterial:input_type -> course.v1.AddMaterialRequest
	20, // 22: course.v1.CourseService.ListMaterials:input_type -> course.v1.ListMaterialsRequest
	22, // 23: course.v1.CourseService.EnrollStudent:input_type -> course.v1.EnrollStudentRequest
	24, // 24: course.v1.CourseService.UnenrollStudent:input_type -> course.v1.UnenrollStudentRequest
	26, // 25: course.v1.CourseService.ListEnrollments:input_type -> course.v1.ListEnrollmentsRequest
	5,  // 26: course.v1.CourseService.CreateCourse:output_type -> course.v1.CreateCourseResponse
	7,  // 27: course.v1.CourseService.GetCourse:output_type -> course.v1.GetCourseResponse
	9,  // 28: course.v1.CourseService.UpdateCourse:output_type -> course.v1.UpdateCourseResponse
	11, // 29: course.v1.CourseService.DeleteCourse:output_type -> course.v1.DeleteCourseResponse
	13, // 30: course.v1.CourseService.ListCourses:output_type -> course.v1.ListCoursesResponse
	15, // 31: course.v1.CourseService.CreateSection:output_type -> course.v1.CreateSectionResponse
	17, // 32: course.v1.CourseService.ListSections:output_type -> course.v1.ListSectionsResponse
	19, // 33: course.v1.CourseService.AddMaterial:output_type -> course.v1.AddMaterialResponse
	21, // 34: course.v1.CourseService.ListMaterials:output_type -> course.v1.ListMaterialsResponse
	23, // 35: course.v1.CourseService.EnrollStudent:output_type -> course.v1.EnrollStudentResponse
	25, // 36: course.v1.CourseService.UnenrollStudent:output_type -> course.v1.UnenrollStudentResponse
	27, // 37: course.v1.CourseService.ListEnrollments:output_type -> course.v1.ListEnrollmentsResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_course_v1_course_proto_init() }
func file_course_v1_course_proto_init() {
	if File_course_v1_course_proto != nil {
		return
	}
	file_course_v1_course_proto_msgTypes[12].OneofWrappers = []any{}
	file_course_v1_course_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_v1_course_proto_rawDesc), len(file_course_v1_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_v1_course_proto_goTypes,
		DependencyIndexes: file_course_v1_course_proto_depIdxs,
		MessageInfos:      file_course_v1_course_proto_msgTypes,
	}.Build()
	File_course_v1_course_proto = out.File
	file_course_v1_course_proto_goTypes = nil
	file_course_v1_course_proto_depIdxs = nil
}
