// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: assessment/v1/assessment.proto

package assessmentv1

import (
	v1 "github.com/Newterios/lms-system-prob/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TimeLimitSec  int32                  `protobuf:"varint,4,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"`
	Shuffle       bool                   `protobuf:"varint,5,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	Questions     []*Question            `protobuf:"bytes,7,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *Quiz) GetShuffle() bool {
	if x != nil {
		return x.Shuffle
	}
	return false
}

func (x *Quiz) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Quiz) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

// Question is used in ALL read responses (GetQuiz, ListQuizzes, StartAttempt, ...).
// No `correct` field — answer key cannot leak to students by construction.
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Choices       []*Choice              `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	Points        int32                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Question) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Question) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// Choice is the read-path shape (inside Question). No `correct` field.
type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // "a", "b", "c", ...
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *Choice) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Choice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ChoiceInput is the write-path shape (inside QuestionInput). Carries `correct`.
type ChoiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Correct       bool                   `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceInput) Reset() {
	*x = ChoiceInput{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceInput) ProtoMessage() {}

func (x *ChoiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceInput.ProtoReflect.Descriptor instead.
func (*ChoiceInput) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *ChoiceInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChoiceInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ChoiceInput) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

// QuestionInput is the write-path shape used only in CreateQuiz requests.
// Uses ChoiceInput so teachers can specify the answer key.
type QuestionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Choices       []*ChoiceInput         `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	Points        int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionInput) Reset() {
	*x = QuestionInput{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionInput) ProtoMessage() {}

func (x *QuestionInput) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionInput.ProtoReflect.Descriptor instead.
func (*QuestionInput) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *QuestionInput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *QuestionInput) GetChoices() []*ChoiceInput {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *QuestionInput) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type Attempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // RFC3339
	SubmittedAt   string                 `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"` // RFC3339, empty until SubmitAttempt
	AutoScore     float64                `protobuf:"fixed64,6,opt,name=auto_score,json=autoScore,proto3" json:"auto_score,omitempty"`
	ManualScore   float64                `protobuf:"fixed64,7,opt,name=manual_score,json=manualScore,proto3" json:"manual_score,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "in_progress" | "submitted" | "graded"
	Answers       []*Answer              `protobuf:"bytes,9,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{5}
}

func (x *Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attempt) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *Attempt) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Attempt) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Attempt) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *Attempt) GetAutoScore() float64 {
	if x != nil {
		return x.AutoScore
	}
	return 0
}

func (x *Attempt) GetManualScore() float64 {
	if x != nil {
		return x.ManualScore
	}
	return 0
}

func (x *Attempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Attempt) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	ChoiceKey     string                 `protobuf:"bytes,2,opt,name=choice_key,json=choiceKey,proto3" json:"choice_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{6}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetChoiceKey() string {
	if x != nil {
		return x.ChoiceKey
	}
	return ""
}

type GradebookEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuizTitle     string                 `protobuf:"bytes,3,opt,name=quiz_title,json=quizTitle,proto3" json:"quiz_title,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "in_progress" | "submitted" | "graded" | "missing"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradebookEntry) Reset() {
	*x = GradebookEntry{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradebookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradebookEntry) ProtoMessage() {}

func (x *GradebookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradebookEntry.ProtoReflect.Descriptor instead.
func (*GradebookEntry) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{7}
}

func (x *GradebookEntry) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GradebookEntry) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *GradebookEntry) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

func (x *GradebookEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradebookEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 1. CreateQuiz
type CreateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TimeLimitSec  int32                  `protobuf:"varint,3,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"`
	Shuffle       bool                   `protobuf:"varint,4,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	Questions     []*QuestionInput       `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{8}
}

func (x *CreateQuizRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuizRequest) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *CreateQuizRequest) GetShuffle() bool {
	if x != nil {
		return x.Shuffle
	}
	return false
}

func (x *CreateQuizRequest) GetQuestions() []*QuestionInput {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CreateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizResponse) Reset() {
	*x = CreateQuizResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizResponse) ProtoMessage() {}

func (x *CreateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateQuizResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// 2. GetQuiz
type GetQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizRequest) Reset() {
	*x = GetQuizRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizRequest) ProtoMessage() {}

func (x *GetQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizRequest.ProtoReflect.Descriptor instead.
func (*GetQuizRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResponse) Reset() {
	*x = GetQuizResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResponse) ProtoMessage() {}

func (x *GetQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResponse.ProtoReflect.Descriptor instead.
func (*GetQuizResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// 3. UpdateQuiz — metadata only; questions are managed separately if/when added.
type UpdateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TimeLimitSec  int32                  `protobuf:"varint,3,opt,name=time_limit_sec,json=timeLimitSec,proto3" json:"time_limit_sec,omitempty"`
	Shuffle       bool                   `protobuf:"varint,4,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateQuizRequest) GetTimeLimitSec() int32 {
	if x != nil {
		return x.TimeLimitSec
	}
	return 0
}

func (x *UpdateQuizRequest) GetShuffle() bool {
	if x != nil {
		return x.Shuffle
	}
	return false
}

type UpdateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizResponse) Reset() {
	*x = UpdateQuizResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizResponse) ProtoMessage() {}

func (x *UpdateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuizResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// 4. DeleteQuiz
type DeleteQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{15}
}

// 5. ListQuizzes
type ListQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuizzesRequest) Reset() {
	*x = ListQuizzesRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizzesRequest) ProtoMessage() {}

func (x *ListQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizzesRequest.ProtoReflect.Descriptor instead.
func (*ListQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{16}
}

func (x *ListQuizzesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ListQuizzesRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuizzesResponse) Reset() {
	*x = ListQuizzesResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizzesResponse) ProtoMessage() {}

func (x *ListQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizzesResponse.ProtoReflect.Descriptor instead.
func (*ListQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{17}
}

func (x *ListQuizzesResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

func (x *ListQuizzesResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// 6. StartAttempt — student_id from JWT.
type StartAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAttemptRequest) Reset() {
	*x = StartAttemptRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAttemptRequest) ProtoMessage() {}

func (x *StartAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAttemptRequest.ProtoReflect.Descriptor instead.
func (*StartAttemptRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{18}
}

func (x *StartAttemptRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type StartAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAttemptResponse) Reset() {
	*x = StartAttemptResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAttemptResponse) ProtoMessage() {}

func (x *StartAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAttemptResponse.ProtoReflect.Descriptor instead.
func (*StartAttemptResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{19}
}

func (x *StartAttemptResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// 7. SubmitAttempt — multi-step write, runs in a DB transaction.
type SubmitAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAttemptRequest) Reset() {
	*x = SubmitAttemptRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAttemptRequest) ProtoMessage() {}

func (x *SubmitAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAttemptRequest.ProtoReflect.Descriptor instead.
func (*SubmitAttemptRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{20}
}

func (x *SubmitAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *SubmitAttemptRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAttemptResponse) Reset() {
	*x = SubmitAttemptResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAttemptResponse) ProtoMessage() {}

func (x *SubmitAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAttemptResponse.ProtoReflect.Descriptor instead.
func (*SubmitAttemptResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{21}
}

func (x *SubmitAttemptResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// 8. GetAttempt
type GetAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptRequest) Reset() {
	*x = GetAttemptRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptRequest) ProtoMessage() {}

func (x *GetAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptRequest.ProtoReflect.Descriptor instead.
func (*GetAttemptRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{22}
}

func (x *GetAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptResponse) Reset() {
	*x = GetAttemptResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptResponse) ProtoMessage() {}

func (x *GetAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptResponse.ProtoReflect.Descriptor instead.
func (*GetAttemptResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{23}
}

func (x *GetAttemptResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// 9. ListAttempts — optional filters.
type ListAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        *string                `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3,oneof" json:"quiz_id,omitempty"`
	StudentId     *string                `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3,oneof" json:"student_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsRequest) Reset() {
	*x = ListAttemptsRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsRequest) ProtoMessage() {}

func (x *ListAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsRequest.ProtoReflect.Descriptor instead.
func (*ListAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{24}
}

func (x *ListAttemptsRequest) GetQuizId() string {
	if x != nil && x.QuizId != nil {
		return *x.QuizId
	}
	return ""
}

func (x *ListAttemptsRequest) GetStudentId() string {
	if x != nil && x.StudentId != nil {
		return *x.StudentId
	}
	return ""
}

func (x *ListAttemptsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      []*Attempt             `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsResponse) Reset() {
	*x = ListAttemptsResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsResponse) ProtoMessage() {}

func (x *ListAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsResponse.ProtoReflect.Descriptor instead.
func (*ListAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{25}
}

func (x *ListAttemptsResponse) GetAttempts() []*Attempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *ListAttemptsResponse) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// 10. GradeSubmission — teacher override; runs in a DB transaction + outbox.
type GradeSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ManualScore   float64                `protobuf:"fixed64,2,opt,name=manual_score,json=manualScore,proto3" json:"manual_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeSubmissionRequest) Reset() {
	*x = GradeSubmissionRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubmissionRequest) ProtoMessage() {}

func (x *GradeSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GradeSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{26}
}

func (x *GradeSubmissionRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *GradeSubmissionRequest) GetManualScore() float64 {
	if x != nil {
		return x.ManualScore
	}
	return 0
}

type GradeSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeSubmissionResponse) Reset() {
	*x = GradeSubmissionResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubmissionResponse) ProtoMessage() {}

func (x *GradeSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubmissionResponse.ProtoReflect.Descriptor instead.
func (*GradeSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{27}
}

func (x *GradeSubmissionResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// 11. GetGradebook
type GetGradebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradebookRequest) Reset() {
	*x = GetGradebookRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradebookRequest) ProtoMessage() {}

func (x *GetGradebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradebookRequest.ProtoReflect.Descriptor instead.
func (*GetGradebookRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{28}
}

func (x *GetGradebookRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetGradebookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*GradebookEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradebookResponse) Reset() {
	*x = GetGradebookResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradebookResponse) ProtoMessage() {}

func (x *GetGradebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradebookResponse.ProtoReflect.Descriptor instead.
func (*GetGradebookResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{29}
}

func (x *GetGradebookResponse) GetEntries() []*GradebookEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// 12. ExportGrades — unary; full CSV in one response.
type ExportGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportGradesRequest) Reset() {
	*x = ExportGradesRequest{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGradesRequest) ProtoMessage() {}

func (x *ExportGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGradesRequest.ProtoReflect.Descriptor instead.
func (*ExportGradesRequest) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{30}
}

func (x *ExportGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ExportGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csv           []byte                 `protobuf:"bytes,1,opt,name=csv,proto3" json:"csv,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportGradesResponse) Reset() {
	*x = ExportGradesResponse{}
	mi := &file_assessment_v1_assessment_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGradesResponse) ProtoMessage() {}

func (x *ExportGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_v1_assessment_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGradesResponse.ProtoReflect.Descriptor instead.
func (*ExportGradesResponse) Descriptor() ([]byte, []int) {
	return file_assessment_v1_assessment_proto_rawDescGZIP(), []int{31}
}

func (x *ExportGradesResponse) GetCsv() []byte {
	if x != nil {
		return x.Csv
	}
	return nil
}

func (x *ExportGradesResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_assessment_v1_assessment_proto protoreflect.FileDescriptor

const file_assessment_v1_assessment_proto_rawDesc = "" +
	"\n" +
	"\x1eassessment/v1/assessment.proto\x12\rassessment.v1\x1a\x16common/v1/common.proto\"\xdf\x01\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12$\n" +
	"\x0etime_limit_sec\x18\x04 \x01(\x05R\ftimeLimitSec\x12\x18\n" +
	"\ashuffle\x18\x05 \x01(\bR\ashuffle\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x125\n" +
	"\tquestions\x18\a \x03(\v2\x17.assessment.v1.QuestionR\tquestions\"w\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12/\n" +
	"\achoices\x18\x03 \x03(\v2\x15.assessment.v1.ChoiceR\achoices\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x05R\x06points\"0\n" +
	"\x06Choice\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"O\n" +
	"\vChoiceInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\"q\n" +
	"\rQuestionInput\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x124\n" +
	"\achoices\x18\x02 \x03(\v2\x1a.assessment.v1.ChoiceInputR\achoices\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\"\x9e\x02\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12!\n" +
	"\fsubmitted_at\x18\x05 \x01(\tR\vsubmittedAt\x12\x1d\n" +
	"\n" +
	"auto_score\x18\x06 \x01(\x01R\tautoScore\x12!\n" +
	"\fmanual_score\x18\a \x01(\x01R\vmanualScore\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12/\n" +
	"\aanswers\x18\t \x03(\v2\x15.assessment.v1.AnswerR\aanswers\"H\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"choice_key\x18\x02 \x01(\tR\tchoiceKey\"\x95\x01\n" +
	"\x0eGradebookEntry\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12\x1d\n" +
	"\n" +
	"quiz_title\x18\x03 \x01(\tR\tquizTitle\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xc2\x01\n" +
	"\x11CreateQuizRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12$\n" +
	"\x0etime_limit_sec\x18\x03 \x01(\x05R\ftimeLimitSec\x12\x18\n" +
	"\ashuffle\x18\x04 \x01(\bR\ashuffle\x12:\n" +
	"\tquestions\x18\x05 \x03(\v2\x1c.assessment.v1.QuestionInputR\tquestions\"=\n" +
	"\x12CreateQuizResponse\x12'\n" +
	"\x04quiz\x18\x01 \x01(\v2\x13.assessment.v1.QuizR\x04quiz\" \n" +
	"\x0eGetQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetQuizResponse\x12'\n" +
	"\x04quiz\x18\x01 \x01(\v2\x13.assessment.v1.QuizR\x04quiz\"y\n" +
	"\x11UpdateQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12$\n" +
	"\x0etime_limit_sec\x18\x03 \x01(\x05R\ftimeLimitSec\x12\x18\n" +
	"\ashuffle\x18\x04 \x01(\bR\ashuffle\"=\n" +
	"\x12UpdateQuizResponse\x12'\n" +
	"\x04quiz\x18\x01 \x01(\v2\x13.assessment.v1.QuizR\x04quiz\"#\n" +
	"\x11DeleteQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteQuizResponse\"h\n" +
	"\x12ListQuizzesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.common.v1.PaginationR\n" +
	"pagination\"v\n" +
	"\x13ListQuizzesResponse\x12-\n" +
	"\aquizzes\x18\x01 \x03(\v2\x13.assessment.v1.QuizR\aquizzes\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo\".\n" +
	"\x13StartAttemptRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\"H\n" +
	"\x14StartAttemptResponse\x120\n" +
	"\aattempt\x18\x01 \x01(\v2\x16.assessment.v1.AttemptR\aattempt\"f\n" +
	"\x14SubmitAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12/\n" +
	"\aanswers\x18\x02 \x03(\v2\x15.assessment.v1.AnswerR\aanswers\"I\n" +
	"\x15SubmitAttemptResponse\x120\n" +
	"\aattempt\x18\x01 \x01(\v2\x16.assessment.v1.AttemptR\aattempt\"#\n" +
	"\x11GetAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12GetAttemptResponse\x120\n" +
	"\aattempt\x18\x01 \x01(\v2\x16.assessment.v1.AttemptR\aattempt\"\xa9\x01\n" +
	"\x13ListAttemptsRequest\x12\x1c\n" +
	"\aquiz_id\x18\x01 \x01(\tH\x00R\x06quizId\x88\x01\x01\x12\"\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tH\x01R\tstudentId\x88\x01\x01\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.common.v1.PaginationR\n" +
	"paginationB\n" +
	"\n" +
	"\b_quiz_idB\r\n" +
	"\v_student_id\"|\n" +
	"\x14ListAttemptsResponse\x122\n" +
	"\battempts\x18\x01 \x03(\v2\x16.assessment.v1.AttemptR\battempts\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo\"Z\n" +
	"\x16GradeSubmissionRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12!\n" +
	"\fmanual_score\x18\x02 \x01(\x01R\vmanualScore\"K\n" +
	"\x17GradeSubmissionResponse\x120\n" +
	"\aattempt\x18\x01 \x01(\v2\x16.assessment.v1.AttemptR\aattempt\"2\n" +
	"\x13GetGradebookRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"O\n" +
	"\x14GetGradebookResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.assessment.v1.GradebookEntryR\aentries\"2\n" +
	"\x13ExportGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"D\n" +
	"\x14ExportGradesResponse\x12\x10\n" +
	"\x03csv\x18\x01 \x01(\fR\x03csv\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xa1\b\n" +
	"\x11AssessmentService\x12Q\n" +
	"\n" +
	"CreateQuiz\x12 .assessment.v1.CreateQuizRequest\x1a!.assessment.v1.CreateQuizResponse\x12H\n" +
	"\aGetQuiz\x12\x1d.assessment.v1.GetQuizRequest\x1a\x1e.assessment.v1.GetQuizResponse\x12Q\n" +
	"\n" +
	"UpdateQuiz\x12 .assessment.v1.UpdateQuizRequest\x1a!.assessment.v1.UpdateQuizResponse\x12Q\n" +
	"\n" +
	"DeleteQuiz\x12 .assessment.v1.DeleteQuizRequest\x1a!.assessment.v1.DeleteQuizResponse\x12T\n" +
	"\vListQuizzes\x12!.assessment.v1.ListQuizzesRequest\x1a\".assessment.v1.ListQuizzesResponse\x12W\n" +
	"\fStartAttempt\x12\".assessment.v1.StartAttemptRequest\x1a#.assessment.v1.StartAttemptResponse\x12Z\n" +
	"\rSubmitAttempt\x12#.assessment.v1.SubmitAttemptRequest\x1a$.assessment.v1.SubmitAttemptResponse\x12Q\n" +
	"\n" +
	"GetAttempt\x12 .assessment.v1.GetAttemptRequest\x1a!.assessment.v1.GetAttemptResponse\x12W\n" +
	"\fListAttempts\x12\".assessment.v1.ListAttemptsRequest\x1a#.assessment.v1.ListAttemptsResponse\x12`\n" +
	"\x0fGradeSubmission\x12%.assessment.v1.GradeSubmissionRequest\x1a&.assessment.v1.GradeSubmissionResponse\x12W\n" +
	"\fGetGradebook\x12\".assessment.v1.GetGradebookRequest\x1a#.assessment.v1.GetGradebookResponse\x12W\n" +
	"\fExportGrades\x12\".assessment.v1.ExportGradesRequest\x1a#.assessment.v1.ExportGradesResponseBGZEgithub.com/Newterios/lms-system-prob/proto/assessment/v1;assessmentv1b\x06proto3"

var (
	file_assessment_v1_assessment_proto_rawDescOnce sync.Once
	file_assessment_v1_assessment_proto_rawDescData []byte
)

func file_assessment_v1_assessment_proto_rawDescGZIP() []byte {
	file_assessment_v1_assessment_proto_rawDescOnce.Do(func() {
		file_assessment_v1_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assessment_v1_assessment_proto_rawDesc), len(file_assessment_v1_assessment_proto_rawDesc)))
	})
	return file_assessment_v1_assessment_proto_rawDescData
}

var file_assessment_v1_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_assessment_v1_assessment_proto_goTypes = []any{
	(*Quiz)(nil),                    // 0: assessment.v1.Quiz
	(*Question)(nil),                // 1: assessment.v1.Question
	(*Choice)(nil),                  // 2: assessment.v1.Choice
	(*ChoiceInput)(nil),             // 3: assessment.v1.ChoiceInput
	(*QuestionInput)(nil),           // 4: assessment.v1.QuestionInput
	(*Attempt)(nil),                 // 5: assessment.v1.Attempt
	(*Answer)(nil),                  // 6: assessment.v1.Answer
	(*GradebookEntry)(nil),          // 7: assessment.v1.GradebookEntry
	(*CreateQuizRequest)(nil),       // 8: assessment.v1.CreateQuizRequest
	(*CreateQuizResponse)(nil),      // 9: assessment.v1.CreateQuizResponse
	(*GetQuizRequest)(nil),          // 10: assessment.v1.GetQuizRequest
	(*GetQuizResponse)(nil),         // 11: assessment.v1.GetQuizResponse
	(*UpdateQuizRequest)(nil),       // 12: assessment.v1.UpdateQuizRequest
	(*UpdateQuizResponse)(nil),      // 13: assessment.v1.UpdateQuizResponse
	(*DeleteQuizRequest)(nil),       // 14: assessment.v1.DeleteQuizRequest
	(*DeleteQuizResponse)(nil),      // 15: assessment.v1.DeleteQuizResponse
	(*ListQuizzesRequest)(nil),      // 16: assessment.v1.ListQuizzesRequest
	(*ListQuizzesResponse)(nil),     // 17: assessment.v1.ListQuizzesResponse
	(*StartAttemptRequest)(nil),     // 18: assessment.v1.StartAttemptRequest
	(*StartAttemptResponse)(nil),    // 19: assessment.v1.StartAttemptResponse
	(*SubmitAttemptRequest)(nil),    // 20: assessment.v1.SubmitAttemptRequest
	(*SubmitAttemptResponse)(nil),   // 21: assessment.v1.SubmitAttemptResponse
	(*GetAttemptRequest)(nil),       // 22: assessment.v1.GetAttemptRequest
	(*GetAttemptResponse)(nil),      // 23: assessment.v1.GetAttemptResponse
	(*ListAttemptsRequest)(nil),     // 24: assessment.v1.ListAttemptsRequest
	(*ListAttemptsResponse)(nil),    // 25: assessment.v1.ListAttemptsResponse
	(*GradeSubmissionRequest)(nil),  // 26: assessment.v1.GradeSubmissionRequest
	(*GradeSubmissionResponse)(nil), // 27: assessment.v1.GradeSubmissionResponse
	(*GetGradebookRequest)(nil),     // 28: assessment.v1.GetGradebookRequest
	(*GetGradebookResponse)(nil),    // 29: assessment.v1.GetGradebookResponse
	(*ExportGradesRequest)(nil),     // 30: assessment.v1.ExportGradesRequest
	(*ExportGradesResponse)(nil),    // 31: assessment.v1.ExportGradesResponse
	(*v1.Pagination)(nil),           // 32: common.v1.Pagination
	(*v1.PageInfo)(nil),             // 33: common.v1.PageInfo
}
var file_assessment_v1_assessment_proto_depIdxs = []int32{
	1,  // 0: assessment.v1.Quiz.questions:type_name -> assessment.v1.Question
	2,  // 1: assessment.v1.Question.choices:type_name -> assessment.v1.Choice
	3,  // 2: assessment.v1.QuestionInput.choices:type_name -> assessment.v1.ChoiceInput
	6,  // 3: assessment.v1.Attempt.answers:type_name -> assessment.v1.Answer
	4,  // 4: assessment.v1.CreateQuizRequest.questions:type_name -> assessment.v1.QuestionInput
	0,  // 5: assessment.v1.CreateQuizResponse.quiz:type_name -> assessment.v1.Quiz
	0,  // 6: assessment.v1.GetQuizResponse.quiz:type_name -> assessment.v1.Quiz
	0,  // 7: assessment.v1.UpdateQuizResponse.quiz:type_name -> assessment.v1.Quiz
	32, // 8: assessment.v1.ListQuizzesRequest.pagination:type_name -> common.v1.Pagination
	0,  // 9: assessment.v1.ListQuizzesResponse.quizzes:type_name -> assessment.v1.Quiz
	33, // 10: assessment.v1.ListQuizzesResponse.page_info:type_name -> common.v1.PageInfo
	5,  // 11: assessment.v1.StartAttemptResponse.attempt:type_name -> assessment.v1.Attempt
	6,  // 12: assessment.v1.SubmitAttemptRequest.answers:type_name -> assessment.v1.Answer
	5,  // 13: assessment.v1.SubmitAttemptResponse.attempt:type_name -> assessment.v1.Attempt
	5,  // 14: assessment.v1.GetAttemptResponse.attempt:type_name -> assessment.v1.Attempt
	32, // 15: assessment.v1.ListAttemptsRequest.pagination:type_name -> common.v1.Pagination
	5,  // 16: assessment.v1.ListAttemptsResponse.attempts:type_name -> assessment.v1.Attempt
	33, // 17: assessment.v1.ListAttemptsResponse.page_info:type_name -> common.v1.PageInfo
	5,  // 18: assessment.v1.GradeSubmissionResponse.attempt:type_name -> assessment.v1.Attempt
	7,  // 19: assessment.v1.GetGradebookResponse.entries:type_name -> assessment.v1.GradebookEntry
	8,  // 20: assessment.v1.AssessmentService.CreateQuiz:input_type -> assessment.v1.CreateQuizRequest
	10, // 21: assessment.v1.AssessmentService.GetQuiz:input_type -> assessment.v1.GetQuizRequest
	12, // 22: assessment.v1.AssessmentService.UpdateQuiz:input_type -> assessment.v1.UpdateQuizRequest
	14, // 23: assessment.v1.AssessmentService.DeleteQuiz:input_type -> assessment.v1.DeleteQuizRequest
	16, // 24: assessment.v1.AssessmentService.ListQuizzes:input_type -> assessment.v1.ListQuizzesRequest
	18, // 25: assessment.v1.AssessmentService.StartAttempt:input_type -> assessment.v1.StartAttemptRequest
	20, // 26: assessment.v1.AssessmentService.SubmitAttempt:input_type -> assessment.v1.SubmitAttemptRequest
	22, // 27: assessment.v1.AssessmentService.GetAttempt:input_type -> assessment.v1.GetAttemptRequest
	24, // 28: assessment.v1.AssessmentService.ListAttempts:input_type -> assessment.v1.ListAttemptsRequest
	26, // 29: assessment.v1.AssessmentService.GradeSubmission:input_type -> assessment.v1.GradeSubmissionRequest
	28, // 30: assessment.v1.AssessmentService.GetGradebook:input_type -> assessment.v1.GetGradebookRequest
	30, // 31: assessment.v1.AssessmentService.ExportGrades:input_type -> assessment.v1.ExportGradesRequest
	9,  // 32: assessment.v1.AssessmentService.CreateQuiz:output_type -> assessment.v1.CreateQuizResponse
	11, // 33: assessment.v1.AssessmentService.GetQuiz:output_type -> assessment.v1.GetQuizResponse
	13, // 34: assessment.v1.AssessmentService.UpdateQuiz:output_type -> assessment.v1.UpdateQuizResponse
	15, // 35: assessment.v1.AssessmentService.DeleteQuiz:output_type -> assessment.v1.DeleteQuizResponse
	17, // 36: assessment.v1.AssessmentService.ListQuizzes:output_type -> assessment.v1.ListQuizzesResponse
	19, // 37: assessment.v1.AssessmentService.StartAttempt:output_type -> assessment.v1.StartAttemptResponse
	21, // 38: assessment.v1.AssessmentService.SubmitAttempt:output_type -> assessment.v1.SubmitAttemptResponse
	23, // 39: assessment.v1.AssessmentService.GetAttempt:output_type -> assessment.v1.GetAttemptResponse
	25, // 40: assessment.v1.AssessmentService.ListAttempts:output_type -> assessment.v1.ListAttemptsResponse
	27, // 41: assessment.v1.AssessmentService.GradeSubmission:output_type -> assessment.v1.GradeSubmissionResponse
	29, // 42: assessment.v1.AssessmentService.GetGradebook:output_type -> assessment.v1.GetGradebookResponse
	31, // 43: assessment.v1.AssessmentService.ExportGrades:output_type -> assessment.v1.ExportGradesResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_assessment_v1_assessment_proto_init() }
func file_assessment_v1_assessment_proto_init() {
	if File_assessment_v1_assessment_proto != nil {
		return
	}
	file_assessment_v1_assessment_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assessment_v1_assessment_proto_rawDesc), len(file_assessment_v1_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assessment_v1_assessment_proto_goTypes,
		DependencyIndexes: file_assessment_v1_assessment_proto_depIdxs,
		MessageInfos:      file_assessment_v1_assessment_proto_msgTypes,
	}.Build()
	File_assessment_v1_assessment_proto = out.File
	file_assessment_v1_assessment_proto_goTypes = nil
	file_assessment_v1_assessment_proto_depIdxs = nil
}
