// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: assessment/v1/assessment.proto

package assessmentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssessmentService_CreateQuiz_FullMethodName      = "/assessment.v1.AssessmentService/CreateQuiz"
	AssessmentService_GetQuiz_FullMethodName         = "/assessment.v1.AssessmentService/GetQuiz"
	AssessmentService_UpdateQuiz_FullMethodName      = "/assessment.v1.AssessmentService/UpdateQuiz"
	AssessmentService_DeleteQuiz_FullMethodName      = "/assessment.v1.AssessmentService/DeleteQuiz"
	AssessmentService_ListQuizzes_FullMethodName     = "/assessment.v1.AssessmentService/ListQuizzes"
	AssessmentService_StartAttempt_FullMethodName    = "/assessment.v1.AssessmentService/StartAttempt"
	AssessmentService_SubmitAttempt_FullMethodName   = "/assessment.v1.AssessmentService/SubmitAttempt"
	AssessmentService_GetAttempt_FullMethodName      = "/assessment.v1.AssessmentService/GetAttempt"
	AssessmentService_ListAttempts_FullMethodName    = "/assessment.v1.AssessmentService/ListAttempts"
	AssessmentService_GradeSubmission_FullMethodName = "/assessment.v1.AssessmentService/GradeSubmission"
	AssessmentService_GetGradebook_FullMethodName    = "/assessment.v1.AssessmentService/GetGradebook"
	AssessmentService_ExportGrades_FullMethodName    = "/assessment.v1.AssessmentService/ExportGrades"
)

// AssessmentServiceClient is the client API for AssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AssessmentService — 12 RPCs from PLAN.md §3.3.
//
// Conventions:
//   - timestamps are RFC3339 strings.
//   - student_id on writes is taken from the JWT — never from the request body.
//   - Two distinct Choice shapes enforce correct-field visibility at the type level:
//     ChoiceInput (write path) carries `correct`; Choice (read path) does not.
//     Leaking the answer key to students is structurally impossible in the proto layer.
//   - ExportGrades is unary — returns the full CSV in one ExportGradesResponse.
//     An optional server-streaming WatchSubmissions sits outside the 12 required
//     RPCs (bonus, see PLAN.md §3.3).
type AssessmentServiceClient interface {
	CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*CreateQuizResponse, error)
	GetQuiz(ctx context.Context, in *GetQuizRequest, opts ...grpc.CallOption) (*GetQuizResponse, error)
	UpdateQuiz(ctx context.Context, in *UpdateQuizRequest, opts ...grpc.CallOption) (*UpdateQuizResponse, error)
	DeleteQuiz(ctx context.Context, in *DeleteQuizRequest, opts ...grpc.CallOption) (*DeleteQuizResponse, error)
	ListQuizzes(ctx context.Context, in *ListQuizzesRequest, opts ...grpc.CallOption) (*ListQuizzesResponse, error)
	StartAttempt(ctx context.Context, in *StartAttemptRequest, opts ...grpc.CallOption) (*StartAttemptResponse, error)
	SubmitAttempt(ctx context.Context, in *SubmitAttemptRequest, opts ...grpc.CallOption) (*SubmitAttemptResponse, error)
	GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*GetAttemptResponse, error)
	ListAttempts(ctx context.Context, in *ListAttemptsRequest, opts ...grpc.CallOption) (*ListAttemptsResponse, error)
	GradeSubmission(ctx context.Context, in *GradeSubmissionRequest, opts ...grpc.CallOption) (*GradeSubmissionResponse, error)
	GetGradebook(ctx context.Context, in *GetGradebookRequest, opts ...grpc.CallOption) (*GetGradebookResponse, error)
	ExportGrades(ctx context.Context, in *ExportGradesRequest, opts ...grpc.CallOption) (*ExportGradesResponse, error)
}

type assessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessmentServiceClient(cc grpc.ClientConnInterface) AssessmentServiceClient {
	return &assessmentServiceClient{cc}
}

func (c *assessmentServiceClient) CreateQuiz(ctx context.Context, in *CreateQuizRequest, opts ...grpc.CallOption) (*CreateQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuizResponse)
	err := c.cc.Invoke(ctx, AssessmentService_CreateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetQuiz(ctx context.Context, in *GetQuizRequest, opts ...grpc.CallOption) (*GetQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuizResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) UpdateQuiz(ctx context.Context, in *UpdateQuizRequest, opts ...grpc.CallOption) (*UpdateQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuizResponse)
	err := c.cc.Invoke(ctx, AssessmentService_UpdateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) DeleteQuiz(ctx context.Context, in *DeleteQuizRequest, opts ...grpc.CallOption) (*DeleteQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuizResponse)
	err := c.cc.Invoke(ctx, AssessmentService_DeleteQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) ListQuizzes(ctx context.Context, in *ListQuizzesRequest, opts ...grpc.CallOption) (*ListQuizzesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuizzesResponse)
	err := c.cc.Invoke(ctx, AssessmentService_ListQuizzes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) StartAttempt(ctx context.Context, in *StartAttemptRequest, opts ...grpc.CallOption) (*StartAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAttemptResponse)
	err := c.cc.Invoke(ctx, AssessmentService_StartAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) SubmitAttempt(ctx context.Context, in *SubmitAttemptRequest, opts ...grpc.CallOption) (*SubmitAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAttemptResponse)
	err := c.cc.Invoke(ctx, AssessmentService_SubmitAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*GetAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttemptResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) ListAttempts(ctx context.Context, in *ListAttemptsRequest, opts ...grpc.CallOption) (*ListAttemptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttemptsResponse)
	err := c.cc.Invoke(ctx, AssessmentService_ListAttempts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GradeSubmission(ctx context.Context, in *GradeSubmissionRequest, opts ...grpc.CallOption) (*GradeSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeSubmissionResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GradeSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetGradebook(ctx context.Context, in *GetGradebookRequest, opts ...grpc.CallOption) (*GetGradebookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGradebookResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetGradebook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) ExportGrades(ctx context.Context, in *ExportGradesRequest, opts ...grpc.CallOption) (*ExportGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGradesResponse)
	err := c.cc.Invoke(ctx, AssessmentService_ExportGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessmentServiceServer is the server API for AssessmentService service.
// All implementations must embed UnimplementedAssessmentServiceServer
// for forward compatibility.
//
// AssessmentService — 12 RPCs from PLAN.md §3.3.
//
// Conventions:
//   - timestamps are RFC3339 strings.
//   - student_id on writes is taken from the JWT — never from the request body.
//   - Two distinct Choice shapes enforce correct-field visibility at the type level:
//     ChoiceInput (write path) carries `correct`; Choice (read path) does not.
//     Leaking the answer key to students is structurally impossible in the proto layer.
//   - ExportGrades is unary — returns the full CSV in one ExportGradesResponse.
//     An optional server-streaming WatchSubmissions sits outside the 12 required
//     RPCs (bonus, see PLAN.md §3.3).
type AssessmentServiceServer interface {
	CreateQuiz(context.Context, *CreateQuizRequest) (*CreateQuizResponse, error)
	GetQuiz(context.Context, *GetQuizRequest) (*GetQuizResponse, error)
	UpdateQuiz(context.Context, *UpdateQuizRequest) (*UpdateQuizResponse, error)
	DeleteQuiz(context.Context, *DeleteQuizRequest) (*DeleteQuizResponse, error)
	ListQuizzes(context.Context, *ListQuizzesRequest) (*ListQuizzesResponse, error)
	StartAttempt(context.Context, *StartAttemptRequest) (*StartAttemptResponse, error)
	SubmitAttempt(context.Context, *SubmitAttemptRequest) (*SubmitAttemptResponse, error)
	GetAttempt(context.Context, *GetAttemptRequest) (*GetAttemptResponse, error)
	ListAttempts(context.Context, *ListAttemptsRequest) (*ListAttemptsResponse, error)
	GradeSubmission(context.Context, *GradeSubmissionRequest) (*GradeSubmissionResponse, error)
	GetGradebook(context.Context, *GetGradebookRequest) (*GetGradebookResponse, error)
	ExportGrades(context.Context, *ExportGradesRequest) (*ExportGradesResponse, error)
	mustEmbedUnimplementedAssessmentServiceServer()
}

// UnimplementedAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssessmentServiceServer struct{}

func (UnimplementedAssessmentServiceServer) CreateQuiz(context.Context, *CreateQuizRequest) (*CreateQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuiz not implemented")
}
func (UnimplementedAssessmentServiceServer) GetQuiz(context.Context, *GetQuizRequest) (*GetQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuiz not implemented")
}
func (UnimplementedAssessmentServiceServer) UpdateQuiz(context.Context, *UpdateQuizRequest) (*UpdateQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuiz not implemented")
}
func (UnimplementedAssessmentServiceServer) DeleteQuiz(context.Context, *DeleteQuizRequest) (*DeleteQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuiz not implemented")
}
func (UnimplementedAssessmentServiceServer) ListQuizzes(context.Context, *ListQuizzesRequest) (*ListQuizzesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuizzes not implemented")
}
func (UnimplementedAssessmentServiceServer) StartAttempt(context.Context, *StartAttemptRequest) (*StartAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAttempt not implemented")
}
func (UnimplementedAssessmentServiceServer) SubmitAttempt(context.Context, *SubmitAttemptRequest) (*SubmitAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAttempt not implemented")
}
func (UnimplementedAssessmentServiceServer) GetAttempt(context.Context, *GetAttemptRequest) (*GetAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttempt not implemented")
}
func (UnimplementedAssessmentServiceServer) ListAttempts(context.Context, *ListAttemptsRequest) (*ListAttemptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttempts not implemented")
}
func (UnimplementedAssessmentServiceServer) GradeSubmission(context.Context, *GradeSubmissionRequest) (*GradeSubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeSubmission not implemented")
}
func (UnimplementedAssessmentServiceServer) GetGradebook(context.Context, *GetGradebookRequest) (*GetGradebookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGradebook not implemented")
}
func (UnimplementedAssessmentServiceServer) ExportGrades(context.Context, *ExportGradesRequest) (*ExportGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportGrades not implemented")
}
func (UnimplementedAssessmentServiceServer) mustEmbedUnimplementedAssessmentServiceServer() {}
func (UnimplementedAssessmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessmentServiceServer will
// result in compilation errors.
type UnsafeAssessmentServiceServer interface {
	mustEmbedUnimplementedAssessmentServiceServer()
}

func RegisterAssessmentServiceServer(s grpc.ServiceRegistrar, srv AssessmentServiceServer) {
	// If the following call panics, it indicates UnimplementedAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssessmentService_ServiceDesc, srv)
}

func _AssessmentService_CreateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).CreateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_CreateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).CreateQuiz(ctx, req.(*CreateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetQuiz(ctx, req.(*GetQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_UpdateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).UpdateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_UpdateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).UpdateQuiz(ctx, req.(*UpdateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_DeleteQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).DeleteQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_DeleteQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).DeleteQuiz(ctx, req.(*DeleteQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_ListQuizzes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuizzesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).ListQuizzes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_ListQuizzes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).ListQuizzes(ctx, req.(*ListQuizzesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_StartAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).StartAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_StartAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).StartAttempt(ctx, req.(*StartAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_SubmitAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).SubmitAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_SubmitAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).SubmitAttempt(ctx, req.(*SubmitAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetAttempt(ctx, req.(*GetAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_ListAttempts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttemptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).ListAttempts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_ListAttempts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).ListAttempts(ctx, req.(*ListAttemptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GradeSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GradeSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GradeSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GradeSubmission(ctx, req.(*GradeSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetGradebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetGradebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetGradebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetGradebook(ctx, req.(*GetGradebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_ExportGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).ExportGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_ExportGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).ExportGrades(ctx, req.(*ExportGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessmentService_ServiceDesc is the grpc.ServiceDesc for AssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assessment.v1.AssessmentService",
	HandlerType: (*AssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuiz",
			Handler:    _AssessmentService_CreateQuiz_Handler,
		},
		{
			MethodName: "GetQuiz",
			Handler:    _AssessmentService_GetQuiz_Handler,
		},
		{
			MethodName: "UpdateQuiz",
			Handler:    _AssessmentService_UpdateQuiz_Handler,
		},
		{
			MethodName: "DeleteQuiz",
			Handler:    _AssessmentService_DeleteQuiz_Handler,
		},
		{
			MethodName: "ListQuizzes",
			Handler:    _AssessmentService_ListQuizzes_Handler,
		},
		{
			MethodName: "StartAttempt",
			Handler:    _AssessmentService_StartAttempt_Handler,
		},
		{
			MethodName: "SubmitAttempt",
			Handler:    _AssessmentService_SubmitAttempt_Handler,
		},
		{
			MethodName: "GetAttempt",
			Handler:    _AssessmentService_GetAttempt_Handler,
		},
		{
			MethodName: "ListAttempts",
			Handler:    _AssessmentService_ListAttempts_Handler,
		},
		{
			MethodName: "GradeSubmission",
			Handler:    _AssessmentService_GradeSubmission_Handler,
		},
		{
			MethodName: "GetGradebook",
			Handler:    _AssessmentService_GetGradebook_Handler,
		},
		{
			MethodName: "ExportGrades",
			Handler:    _AssessmentService_ExportGrades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assessment/v1/assessment.proto",
}
